"""ok

Revision ID: 61207aeb992c
Revises: 93e0c008aac1
Create Date: 2025-10-31 01:58:59.468205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61207aeb992c'
down_revision = '93e0c008aac1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('size', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_column('size')
        batch_op.drop_column('color')

    # ### end Alembic commands ###
