"""inventory

Revision ID: d34c848c551d
Revises: 2a3b629e31d2
Create Date: 2025-10-31 06:04:01.900667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd34c848c551d'
down_revision = '2a3b629e31d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('packaging_cost', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('product_cost', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('selling_cost', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('supplier_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('supplier_address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('supplier_contact', sa.String(length=50), nullable=True))
        batch_op.alter_column('price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('image',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)
        batch_op.alter_column('price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.drop_column('supplier_contact')
        batch_op.drop_column('supplier_address')
        batch_op.drop_column('supplier_name')
        batch_op.drop_column('selling_cost')
        batch_op.drop_column('product_cost')
        batch_op.drop_column('packaging_cost')
        batch_op.drop_column('stock')

    # ### end Alembic commands ###
